language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install flake8
before_script:
  - python setup.py flake8
script:
  python setup.py install
after_success:
  - |
    if [[ "${TRAVIS_TAG:-}" != ""]]; then
      python setup.py sdist bdist_wheel;
      python -m pip install twine;
      python -m twine upload --skip-existing dist/*;
    fi