language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install flake8
script:
  - python setup.py flake8
after_success:
  - |
    if [[ "${TRAVIS_TAG:-}" != "" ]]; then
      python3.6 setup.py sdist bdist_wheel;
      python3.6 -m pip install twine;
      python3.6 -m twine upload --skip-existing dist/*;
    fi
